### ISSUE TITLE
Migrate Mongo to mLab

### ISSUE THREAD

**Issue by sidhshar** [S3Infosoft/mvr-call-operator#7]
https://mlab.com/plans/pricing/#plan-type=sandbox

**Comment by PersonablePhaniK** [comment]
Can I use my personal account in mlab.com (or) any company registered account to migrate the MongoDB?
Please advice.

**Comment by PersonablePhaniK** [comment]
Thanks for giving access to the MongoDB-Atlas. I'll move local-db to cloud and reference the connection string to point to Atlas-db, once the data-sync is completed

**Comment by PersonablePhaniK** [comment]
Hi Sidhartha,


I don't have enough access to create db_user and add my IP address to whitelist app access.


To migrate local db (or) update application access to cloud db, I need to have 'read, write' privileges, recommended access will be of 'admin' in-case  I face issue during the migration.


Please do the needful.


Regards,
Phani

**Comment by sidhshar** [comment]
I have provided you owner access. Can you check now?

**Comment by PersonablePhaniK** [comment]
Thank you soo much. I got the access, able to create new db_user and whitelist my IP for application access. working on moving local DB to the cloud.

**Comment by PersonablePhaniK** [comment]
successfully migrated local DB to the cloud(atlas).
![image](https://user-images.githubusercontent.com/61106109/80589379-adaf4280-8a37-11ea-86a2-7de8e439b35b.png)
