### ISSUE TITLE
Call operator data sync

### ISSUE THREAD

**Issue by sidhshar** [S3Infosoft/mvr-call-operator#9]
1. Learn about Unix timestamps. The call operator API already provides these. For E.g. what would be timestamp for 1st Oct, 31st Oct, 1st Nov, 30th Nov, etc.
2. Invoke API for these months in 2019 October, November, December using the from, to parameters.
3. Then invoke API for Jan, Feb and March in 2020 using from, to parameters/
3. Daily API call: For April, make API call for every day i.e. 1st, 2nd using timestamps again from 12AM to 12AM.
4. How do we run these regularly every night to get data per day? Think about Date selection screen (From date calendar widget, To date calendar widget, Sync button) to sync entries from UI.

**Comment by PersonablePhaniK** [comment]
Able to create express API to Invoke call operator API using 'From' & 'To' date filters. Working on adding date picker widget to UI

**Comment by PersonablePhaniK** [comment]
Data-sync from API to DB for the dates from 1st Oct 2019 - till date is done. Attached screenshot for the reference. 

Note: Working on daily incremental data load using automatic schedule libraries 
![data_sync](https://user-images.githubusercontent.com/61106109/80057145-893cfd00-8543-11ea-876e-24bcb6944600.png)

**Comment by PersonablePhaniK** [comment]
working on automating increment data load from myoperator API to DB

**Comment by PersonablePhaniK** [comment]
Automated increment data loading is working, this would execute daily at 1am, check for data from previous day from 12am to today 12am. This would run at the schedule once we host the backend to live server.
